---
kind: pipeline
name: tests-python-3.8-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: tests
  image: python:3.8
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
  commands:
    - export CYTHON_IGNORE=true
    - pip install --extra-index-url $OCTOBOT_PYPI_URL --prefer-binary -r dev_requirements.txt -r requirements.txt
    - python3 setup.py install
    - pytest --cov=. --cov-config=.coveragerc --durations=0 -rw tests
